### ISSUE TITLE
Update to 2019/2020

### ISSUE THREAD

**Issue by nrfulton** [nrfulton/pittdoggos#1]
The README and code is written for the 2018 data set. However, the link to the original dataset is broken and and I'm not sure the processing scripts will work for the 2019 data set.

Todo:

1. Find the 2019 or 2020 dataset, whichever is most recent and available.

2. Update readme with working leaks.

3. If necessary, update the processing scripts.

**Comment by Ankursharma-coder** [comment]
hi

**Comment by Abhishek4uh** [comment]
Hey @nrfulton! Can I work on this?

**Comment by Bharadwaja92** [comment]
Hi @nrfulton Can I work on this issue? I have the datasets of 2019 and 2020 available with me.

**Comment by rajat1401** [comment]
Hi @nrfulton I worked on the issue and have made the PR https://github.com/nrfulton/pittdoggos/pull/3 for the same. Please review and merge.

**Comment by Bharadwaja92** [comment]
Hi @rajat1401 We have to wait for the maintainer @nrfulton to assign this issue before working on it.
